# Builds the four resort buildings and re-exports assets/models/buildings.glb.
#
# This file exists because the buildings did not have one. Every other model in
# the game is generated by a script; these four were made by hand in a live
# Blender session, nobody rendered them afterwards, and all three pitched roofs
# went in inside out — a wedge dipping into the building instead of a ridge over
# it, with the walls left open at the top. A bounding box cannot see that, which
# is why it survived a playtest.
#
# The groomer lives in the same file and is fine, so it is imported from the
# existing .glb and re-exported untouched.
#
#   /Applications/Blender.app/Contents/MacOS/Blender --background \
#       --python tools/build_buildings.py
#
# Two contracts the game relies on:
#   * The doorway faces the game's +Z, which is Blender's -Y. (Blender exports
#     (x, y, z) as (x, z, -y), so a model built facing +Y arrives facing away.)
#   * The origin sits on the ground at the centre of the footprint, because the
#     resort drops each building at a sampled terrain height.

import bpy, math, os

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MODELS = os.path.join(HERE, "assets", "models")
GLB = os.path.join(MODELS, "buildings.glb")

# ------------------------------------------------------------------ materials


def mat(name, colour, rough=0.8, metal=0.0):
    m = bpy.data.materials.get(name) or bpy.data.materials.new(name)
    m.use_nodes = True
    b = m.node_tree.nodes["Principled BSDF"]
    b.inputs["Base Color"].default_value = (*colour, 1.0)
    b.inputs["Roughness"].default_value = rough
    b.inputs["Metallic"].default_value = metal
    return m


def build_materials():
    return {
        "wood": mat("Wood", (0.190, 0.115, 0.062), 0.82),
        "woodl": mat("WoodLight", (0.330, 0.215, 0.128), 0.78),
        "stone": mat("Stone", (0.120, 0.118, 0.112), 0.90),
        "roof": mat("RoofSlate", (0.043, 0.050, 0.060), 0.62),
        "snow": mat("SnowLoad", (0.780, 0.820, 0.880), 0.74),
        "glass": mat("Glazing", (0.030, 0.055, 0.085), 0.10, 0.25),
        "steel": mat("Steel", (0.42, 0.44, 0.47), 0.38, 1.0),
        "galv": mat("Galvanised", (0.60, 0.62, 0.65), 0.55, 1.0),
        "paint": mat("PaintYellow", (0.86, 0.58, 0.06), 0.42),
        "trim": mat("PaintWhite", (0.86, 0.88, 0.91), 0.45),
        "lamp": mat("Lamp", (1.0, 0.86, 0.55), 0.35),
    }


# ------------------------------------------------------------------ geometry
#
# Everything is assembled from explicit vertex lists. It is more typing than
# primitives-and-modifiers, but a gable written as six named corners cannot come
# out upside down, and that is the entire point of this file.


class Builder:
    def __init__(self):
        self.verts = []
        self.faces = []
        self.mats = []

    def add(self, verts, faces, mi):
        base = len(self.verts)
        self.verts.extend(verts)
        for f in faces:
            self.faces.append(tuple(base + i for i in f))
            self.mats.append(mi)

    def box(self, cx, cy, cz, hx, hy, hz, mi):
        v = [
            (cx - hx, cy - hy, cz - hz), (cx + hx, cy - hy, cz - hz),
            (cx + hx, cy + hy, cz - hz), (cx - hx, cy + hy, cz - hz),
            (cx - hx, cy - hy, cz + hz), (cx + hx, cy - hy, cz + hz),
            (cx + hx, cy + hy, cz + hz), (cx - hx, cy + hy, cz + hz),
        ]
        f = [(0, 3, 2, 1), (4, 5, 6, 7), (0, 1, 5, 4),
             (1, 2, 6, 5), (2, 3, 7, 6), (3, 0, 4, 7)]
        self.add(v, f, mi)

    def gable_prism(self, cx, cy, hx, hy, z0, z1, mi, zb=0.0):
        """A solid whose cross-section is a house end: walls up to z0, ridge at z1.

        The ridge runs along Y. This is the piece that decides which way a roof
        points, so it is written as five explicit corners per end rather than
        rotated into place.
        """
        v = [
            (cx - hx, cy - hy, zb), (cx + hx, cy - hy, zb),
            (cx + hx, cy - hy, z0), (cx, cy - hy, z1), (cx - hx, cy - hy, z0),
            (cx - hx, cy + hy, zb), (cx + hx, cy + hy, zb),
            (cx + hx, cy + hy, z0), (cx, cy + hy, z1), (cx - hx, cy + hy, z0),
        ]
        f = [
            (0, 4, 3, 2, 1), (5, 6, 7, 8, 9),          # the two gable ends
            (0, 1, 6, 5), (1, 2, 7, 6), (2, 3, 8, 7),   # base and the two eaves
            (3, 4, 9, 8), (4, 0, 5, 9),
        ]
        self.add(v, f, mi)

    def roof_plane(self, cx, cy, hx, hy, z_eave, z_ridge, thick, mi, side):
        """One slope of a gable roof, as a slab with real thickness.

        `side` is -1 for the slope falling towards -X and +1 for +X. The ridge is
        ALWAYS the high edge: there is no argument that can make this dip.
        """
        rx = cx
        ex = cx + side * hx
        v = [
            (rx, cy - hy, z_ridge), (ex, cy - hy, z_eave),
            (ex, cy + hy, z_eave), (rx, cy + hy, z_ridge),
            (rx, cy - hy, z_ridge - thick), (ex, cy - hy, z_eave - thick),
            (ex, cy + hy, z_eave - thick), (rx, cy + hy, z_ridge - thick),
        ]
        f = [(0, 1, 2, 3), (7, 6, 5, 4), (0, 4, 5, 1),
             (1, 5, 6, 2), (2, 6, 7, 3), (3, 7, 4, 0)]
        self.add(v, f, mi)

    def to_object(self, name, materials):
        me = bpy.data.meshes.new(name)
        me.from_pydata(self.verts, [], self.faces)
        ob = bpy.data.objects.new(name, me)
        bpy.context.collection.objects.link(ob)
        for m in materials:
            me.materials.append(m)
        for i, poly in enumerate(me.polygons):
            poly.material_index = self.mats[i]
        me.validate()
        # Everything is built convex-outward, so a single recalculate leaves every
        # normal pointing out and nothing renders inside-out.
        me.update()
        return ob


# ------------------------------------------------------------------ buildings


def chalet(name, M, width, depth, wall_h, roof_rise, overhang=0.7,
           plinth=0.55, door_w=1.9, door_h=2.3, windows=(), balcony=False,
           chimney=False, sign_colour=None):
    """A timber alpine building: stone plinth, timber box, gable roof over it.

    The ridge runs along the depth axis (Y in Blender), so both roof slopes face
    left and right and the door is in a gable end — which is why the doorway can
    be tall and the eaves still clear it.
    """
    b = Builder()
    order = ["wood", "woodl", "stone", "roof", "snow", "glass", "trim", "lamp"]
    mi = {k: i for i, k in enumerate(order)}
    mats = [M[k] for k in order]

    hx, hy = width / 2, depth / 2
    z_wall = plinth + wall_h
    z_ridge = z_wall + roof_rise

    b.box(0, 0, plinth / 2, hx + 0.16, hy + 0.16, plinth / 2, mi["stone"])
    # Walls and the gable triangle as ONE solid, so the top of the building is
    # closed. Built as two thin pieces it looks right until the camera gets under
    # the eaves and finds you can see into an empty shell.
    b.gable_prism(0, 0, hx, hy, z_wall, z_ridge, mi["wood"], zb=plinth)
    # The gable face gets the lighter timber, laid on as a shallow panel.
    for end_y, out in ((-hy, -1), (hy, 1)):
        b.gable_prism(0, end_y + out * 0.05, hx * 0.98, 0.05,
                      z_wall + 0.02, z_ridge - 0.06, mi["woodl"], zb=z_wall - 0.02)

    # The roof: two slabs meeting at the ridge, overhanging on every side.
    ro_x, ro_y = hx + overhang, hy + overhang
    # Keep the pitch of the overhang the same as the pitch of the roof.
    pitch = roof_rise / hx
    z_eave = z_wall - overhang * pitch
    for side in (-1, 1):
        b.roof_plane(0, 0, ro_x, ro_y, z_eave, z_ridge, 0.18, mi["roof"], side)
        # Snow sits on the roof, so it is the same two planes lifted a little —
        # never its own shape, which is how the old model ended up with snow in a
        # ridge above a roof in a trough.
        b.roof_plane(0, 0, ro_x * 0.985, ro_y * 0.985,
                     z_eave + 0.20, z_ridge + 0.20, 0.14, mi["snow"], side)

    # Ridge cap, and a bargeboard down each gable edge. The board is ONE sloped
    # slab per side: cutting the slope into little boxes gives a row of teeth,
    # which is what it gave the first time.
    b.box(0, 0, z_ridge + 0.08, 0.13, ro_y, 0.10, mi["trim"])
    for end_y in (-1, 1):
        for side in (-1, 1):
            b.roof_plane(0, end_y * (ro_y - 0.06), ro_x, 0.06,
                         z_eave - 0.20, z_ridge - 0.20, 0.13, mi["trim"], side)

    # Doorway in the -Y gable, which is the game's +Z.
    b.box(0, -hy - 0.05, plinth + door_h / 2, door_w / 2 + 0.11, 0.06,
          door_h / 2 + 0.10, mi["woodl"])
    b.box(0, -hy - 0.11, plinth + door_h / 2, door_w / 2 - 0.04, 0.04,
          door_h / 2 - 0.04, mi["glass"])
    # A lamp over the door, so the entrance reads at dusk.
    b.box(0, -hy - 0.22, plinth + door_h + 0.30, 0.16, 0.14, 0.13, mi["lamp"])

    for (wx, wy, ww, wh, wz) in windows:
        # wy is -1 for the front gable, +1 for the back, 0 for a long side.
        if wy == 0:
            b.box(wx * hx, 0, plinth + wz, 0.05, ww / 2, wh / 2, mi["glass"])
            b.box(wx * (hx - 0.02), 0, plinth + wz, 0.04, ww / 2 + 0.10,
                  wh / 2 + 0.10, mi["trim"])
        else:
            b.box(wx, wy * (hy + 0.04), plinth + wz, ww / 2, 0.05, wh / 2, mi["glass"])
            b.box(wx, wy * (hy + 0.02), plinth + wz, ww / 2 + 0.10, 0.04,
                  wh / 2 + 0.10, mi["trim"])

    if balcony:
        # On the BACK gable. On the front it hangs across the doorway, which is
        # both ugly and the one part of the building that has to stay legible.
        by = hy + 0.80
        deck = plinth + wall_h * 0.60
        b.box(0, by - 0.40, deck, hx * 0.92, 0.82, 0.09, mi["woodl"])
        for i in range(9):
            x = -hx * 0.86 + (i / 8) * hx * 1.72
            b.box(x, by + 0.34, deck + 0.44, 0.05, 0.05, 0.44, mi["woodl"])
        b.box(0, by + 0.34, deck + 0.90, hx * 0.92, 0.07, 0.06, mi["woodl"])
        # Brackets, so it is holding itself up rather than floating.
        for x in (-hx * 0.7, 0, hx * 0.7):
            b.box(x, by - 0.42, deck - 0.34, 0.06, 0.60, 0.30, mi["woodl"])

    if chimney:
        b.box(hx * 0.45, hy * 0.3, z_ridge - 0.2, 0.42, 0.42, roof_rise * 0.7 + 0.6, mi["stone"])
        b.box(hx * 0.45, hy * 0.3, z_ridge + roof_rise * 0.5 + 0.42, 0.52, 0.52, 0.10, mi["stone"])

    if sign_colour:
        # Above the door, under the gable — not across the doorway.
        b.box(0, -hy - 0.13, plinth + door_h + 0.72, hx * 0.42, 0.09, 0.30, mi[sign_colour])

    return b.to_object(name, mats)


def garage(name, M, width=14.0, depth=17.0, wall_h=5.6, roof_rise=1.5):
    """The machine shed. Steel, shallow pitch, and a door big enough for a groomer."""
    b = Builder()
    order = ["galv", "steel", "snow", "paint", "stone", "glass"]
    mi = {k: i for i, k in enumerate(order)}
    mats = [M[k] for k in order]

    hx, hy = width / 2, depth / 2
    z_wall = wall_h
    z_ridge = z_wall + roof_rise

    b.box(0, 0, 0.14, hx + 0.2, hy + 0.2, 0.14, mi["stone"])
    b.gable_prism(0, 0, hx, hy, z_wall, z_ridge, mi["galv"], zb=0.28)

    over = 0.45
    pitch = roof_rise / hx
    z_eave = z_wall - over * pitch
    for side in (-1, 1):
        b.roof_plane(0, 0, hx + over, hy + over, z_eave, z_ridge, 0.16, mi["steel"], side)
        b.roof_plane(0, 0, (hx + over) * 0.98, (hy + over) * 0.98,
                     z_eave + 0.18, z_ridge + 0.18, 0.12, mi["snow"], side)

    # Roller door, in the -Y wall — the game's +Z, same as every other doorway.
    door_w, door_h = 8.2, 4.6
    b.box(0, -hy - 0.10, 0.28 + door_h / 2, door_w / 2, 0.10, door_h / 2, mi["steel"])
    for i in range(9):
        z = 0.28 + (i + 0.5) / 9 * door_h
        b.box(0, -hy - 0.19, z, door_w / 2 - 0.05, 0.03, door_h / 20, mi["galv"])
    b.box(0, -hy - 0.16, 0.28 + door_h + 0.36, door_w / 2 + 0.35, 0.14, 0.26, mi["paint"])

    # A window in each long wall, so it is not a windowless crate.
    for side in (-1, 1):
        for oy in (-hy * 0.45, hy * 0.35):
            b.box(side * (hx + 0.03), oy, 0.28 + wall_h * 0.72, 0.05, 1.1, 0.55, mi["glass"])

    return b.to_object(name, mats)


# ------------------------------------------------------------------ assembly

def main():
    # Start from the shipped file so the groomer survives untouched: it is the one
    # thing in here that was already right, and rebuilding it would be a second
    # chance to break something that works.
    for o in list(bpy.data.objects):
        bpy.data.objects.remove(o, do_unlink=True)
    bpy.ops.import_scene.gltf(filepath=GLB)
    keep = [o for o in bpy.context.scene.objects if o.name.startswith("groomer")]
    for o in list(bpy.context.scene.objects):
        top = o
        while top.parent is not None:
            top = top.parent
        if top.name.startswith("bld_"):
            bpy.data.objects.remove(o, do_unlink=True)
    print("kept:", [o.name for o in keep])

    M = build_materials()

    chalet("bld_rental", M, width=16.0, depth=12.0, wall_h=3.6, roof_rise=2.9,
           door_w=2.4, door_h=2.5, balcony=False, sign_colour="trim",
           windows=[(-3.6, -1, 1.6, 1.2, 1.7), (3.6, -1, 1.6, 1.2, 1.7),
                    (-1, 0, 3.0, 1.3, 1.8), (1, 0, 3.0, 1.3, 1.8)])

    chalet("bld_cafe", M, width=14.0, depth=15.0, wall_h=4.4, roof_rise=3.3,
           door_w=2.0, door_h=2.4, balcony=True, chimney=True, sign_colour="trim",
           windows=[(-3.2, -1, 2.0, 1.5, 1.6), (3.2, -1, 2.0, 1.5, 1.6),
                    (-1, 0, 4.0, 1.5, 1.8), (1, 0, 4.0, 1.5, 1.8),
                    (0, 1, 2.4, 1.2, 1.7)])

    chalet("bld_booth", M, width=6.0, depth=5.6, wall_h=2.8, roof_rise=1.6,
           overhang=0.55, door_w=1.7, door_h=2.1, sign_colour="trim",
           windows=[(-1.9, -1, 1.1, 0.9, 1.5), (1.9, -1, 1.1, 0.9, 1.5),
                    (-1, 0, 1.8, 1.0, 1.6), (1, 0, 1.8, 1.0, 1.6)])

    garage("bld_garage", M)

    for o in bpy.context.scene.objects:
        o.select_set(True)
    bpy.ops.export_scene.gltf(
        filepath=GLB, export_format="GLB", use_selection=True,
        export_apply=True, export_yup=True,
    )
    print("wrote", GLB)


main()
